version: '2'

services:
 app0:
  image: dottgonzo/ubunodedocker
  restart: always
  command: '/bin/sh -c "rm -rf ./express-example && sync && git clone https://github.com/sequelize/express-example.git && cd ./express-example && npm i --production && forever start ./bin/www && /bin/sh"'
  ports:
   - 3000:3000
   
 app1:
  image: dottgonzo/mininode
  restart: always
  command: '/bin/sh -c "rm -rf ./express-example && sync && git clone https://github.com/sequelize/express-example.git && cd ./express-example && npm i --production && forever start ./bin/www && /bin/sh"'
  ports:
   - 4000:3000
   
 app2:
  image: dottgonzo/httpdgitdocker
  restart: always
  command: '/bin/sh -c "rm -rf /usr/local/apache2/htdocs/public-html && sync && git clone https://github.com/sequelize/express-example.git /usr/local/apache2/htdocs/public-html && chmod 777 -R /usr/local/apache2/htdocs/public-html && /bin/sh"'
  ports:
   - 4155:80
  tty: true
   
   
   
   