version: '2'

services:
 app0:
  image: dottgonzo/ubunodedocker
  command: 'bash -c "git clone https://github.com/sequelize/express-example.git . && npm i --production && forever start"'
  ports:
   - 3000:3000
   
