version: '2'

services:
 app0:
  image: dottgonzo/ubunodedocker
  restart: on_failure
  command: '/bin/sh -c "git clone https://github.com/sequelize/express-example.git . && npm i --production && npm start"'
  ports:
   - 3000:3000
   
 app1:
  image: dottgonzo/mininode
  restart: on_failure
  command: '/bin/sh -c "git clone https://github.com/sequelize/express-example.git . && npm i --production && npm start"'
  ports:
   - 4000:3000