version: '2'

services:
 app0:
  image: dottgonzo/ubunodedocker
  restart: always
  command: '/bin/sh -c "rm -rf /usr/local/apache2/htdocs/public-html && sync && git clone https://github.com/sequelize/express-example.git /usr/local/apache2/htdocs/public-html"'
  ports:
   - 8000:80
   
 app1:
  image: dottgonzo/mininode
  restart: always
  command: '/bin/sh -c "rm -rf ./express-example && sync && git clone https://github.com/sequelize/express-example.git && cd ./express-example && npm i --production && sync && npm start"'
  ports:
   - 4000:3000
   
 app2:
  image: httpd
  restart: always
  command: '/bin/sh -c "rm -rf ./express-example && sync && git clone https://github.com/sequelize/express-example.git && cd ./express-example && npm i --production && sync && npm start"'
  ports:
   - 4000:3000
   
   
   
   